### ISSUE TITLE
Username change

### ISSUE THREAD

**Issue by GirafiStudios** [girafi/module-loader-experiment#4]
Hey there!
I was wondering if I perhaps could get you to change your username here on Github ? :)

Sincerely Girafi.

**Comment by girafi** [comment]
hi there,

Glad to hear there's another Girafi around in the world :)
Where are your from?

I'm sorry to refuse, I've been having this username on all my accounts on
all platforms since the beginnings of the internet, and would actually be
grateful if I could keep it.

Best Regards from Switzerland

: girafi

**Comment by GirafiStudios** [comment]
Alright :)

I just figured if you didn't really care about your username, there might have been a chance!

And i'm from Denmark. I have also been using Girafi for a really long time, about 10 years or so :)
